export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

//View Forum
export const FETCHING_POSTS_REQUEST = 'FETCHING_POSTS_REQUEST';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAILURE = 'FETCHING_POSTS_FAILURE';

//Add Post
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const APPEND_NEW_POST = 'APPEND_NEW_POST';

//Add Comment
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_POST_FAILURE';
export const APPEND_NEW_COMMENT = 'APPEND_NEW_COMMENT';
export const UPDATE_NEW_COMMENT = 'UPDATE_NEW_COMMENT';

//Fetch Post Comments
export const FETCHING_POST_COMMENTS_REQUEST = 'FETCHING_POST_COMMENTS_REQUEST';
export const FETCHING_POST_COMMENTS_SUCCESS = 'FETCHING_POST_COMMENTS_SUCCESS';
export const FETCHING_POST_COMMENTS_FAILURE = 'FETCHING_POST_COMMENTS_FAILURE';

//Fetch User Points
export const FETCH_USER_POINTS_DETAILS_REQUEST = 'FETCH_USER_POINTS_DETAILS_REQUEST';
export const FETCH_USER_POINTS_DETAILS_SUCCESS = 'FETCH_USER_POINTS_DETAILS_SUCCESS';
export const FETCH_USER_POINTS_DETAILS_FAILURE = 'FETCH_USER_POINTS_DETAILS_FAILURE';

// Fetch User Points History
export const FETCH_USER_POINT_HISTORY_REQUEST = 'FETCH_USER_POINT_HISTORY_REQUEST';
export const FETCH_USER_POINT_HISTORY_SUCCESS = 'FETCH_USER_POINT_HISTORY_SUCCESS';
export const FETCH_USER_POINT_HISTORY_FAILURE = 'FETCH_USER_POINT_HISTORY_FAILURE';

//Fetch User Trophies
export const FETCH_USER_TROPHIES_REQUEST = 'FETCH_USER_TROPHIES_REQUEST';
export const FETCH_USER_TROPHIES_SUCCESS = 'FETCH_USER_TROPHIES_SUCCESS';
export const FETCH_USER_TROPHIES_FAILURE = 'FETCH_USER_TROPHIES_FAILURE';

//Fetch Products
export const FETCH_RECOMMENDED_PRODUCTS_REQUEST = 'FETCH_RECOMMENDED_PRODUCTS_REQUEST';
export const FETCH_RECOMMENDED_PRODUCTS_SUCCESS = 'FETCH_RECOMMENDED_PRODUCTS_SUCCESS';
export const FETCH_RECOMMENDED_PRODUCTS_FAILURE = 'FETCH_RECOMMENDED_PRODUCTS_FAILURE';

//Search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET';
export const ERROR_RESET = 'ERROR_RESET';

//Recent Search
export const RECENT_SEARCH_REQUEST = 'RECENT_SEARCH_REQUEST';
export const RECENT_SEARCH_SUCCESS = 'RECENT_SEARCH_SUCCESS';
export const RECENT_SEARCH_FAILURE = 'RECENT_SEARCH_FAILURE';